### ISSUE TITLE
ping reply packet ?

### ISSUE THREAD

**Issue by respectZ** [GrowtopiaNoobs/Growtopia-Bot#45]
So, I tried to implement send ping whenever server requested it. At first, it went smoothly. But, after 50 minutes or later, I checked my bots and they got autoban. Here is my code
```
PlayerMoving* ping = new PlayerMoving;
ping->packetType = 21; //ping reply
ping->x = 64.f;
ping->y = 64.f;
ping->xSpeed = 1000.f;
ping->ySpeed = 250.f;
ping->netID = 0;
SendPacketRaw(4, packPlayerMoving(ping), 56, 0, peer, 1);
```
Was the value wrong ? Or did I miss something ?

**Comment by RefetB** [comment]
Ping packet have been used for checking user status.If you are doing something extreme (needs to use complicated packet) server bans you auto.It's same as when you became afk with your main,you will get disconnected after some minutes.Maybe you should check it a bit more deeper.Like what happens when they getting auto banned.
EDIT:And you are using wrong types.Example you should use 1byte for packetType.

**Comment by respectZ** [comment]
Well, thanks for the explanation. I'll try to dig it deeper and use 1 byte for packetType.
If you have implemented ping packet, may I have a look ?

**Comment by RefetB** [comment]
I did in really another way.You should use a proxy and see what happens when gt sends ping reply.You should check ama6en's proxy.I don't use normal playermoving packet too.I can help with saying what to do,but I won't show my code sorry.

**Comment by respectZ** [comment]
Okay, It's fine. I used ama6nen's proxy to determine ping reply and did same exactly. Maybe I'm still missing a piece of code though. Thanks a lot !

**Comment by RefetB** [comment]
Np
